name: 'Setup'
description: 'Setup node, dependencies and cache'

inputs:
  node_version:
    description: 'Node version to use'
    default: '20.11.1'

runs:
  using: composite
  steps:
    - name: "Setup node env"
      id: node
      uses: actions/setup-node@v4
      with:
        cache: 'yarn'
        node-version: ${{ inputs.node_version }}

    - name: "Install dependencies"
      run: yarn install --immutable
      shell: bash


