# Cache dependencies when merged on main to make them available to all new PRs

on:
  push:
    branches:
      - main

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Setup node & dependencies"
        uses: ./.github/actions/setup
